# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('target', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=15, max_digits=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UnconfirmedTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('target', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=15, max_digits=20)),
            ],
        ),
    ]
