# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przelewy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='title',
            field=models.TextField(default='Przelew'),
        ),
        migrations.AddField(
            model_name='unconfirmedtransfer',
            name='title',
            field=models.TextField(default='Przelew'),
        ),
    ]
